language: android
env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-23.0.1
    - android-23
    - platform-tools
    - tools
    - extra
    - sys-img-armeabi-v7a-android-19
    - addon-google_apis-google-19

  licenses:
    - 'android-sdk-license-.+'


script: ./gradlew connectedDebugAndroidTest --info --stacktrace
