language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

sudo: false

android:
  components:
    - build-tools-23.0.1
    - android-23
    - platform-tools
    - tools
    - extra
    - sys-img-armeabi-v7a-android-19

  licenses:
    - 'android-sdk-license-.+'

before_script:
    - chmod +x gradlew
    - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    - adb wait-for-device
    - adb shell input keyevent 82 &

script:
  - android list target
  - ./gradlew connectedAndroidTest -PdisablePreDex
